# Generated by Django 4.2.6 on 2023-10-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ImageField(blank=True, null=True, upload_to='orders/photos/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/photos'),
        ),
    ]
